### ISSUE TITLE
【Feature】提供配置用以控制跳过unocss样式检测，直接生成所有已配置的css变量

### ISSUE THREAD

**Issue by itmanyong** [unpreset/unocss-preset-theme#67]
例如以下预设和使用
```js
{
  theme:{
    colors:{
      red: 'red',
      green: 'green'
    }
  },
  presets: [
    presetUno(),
    presetTheme({
      prefix: '--theme',
      theme: {
        light: {
          red: 'red',
          green: 'green'
        }
      }
    })
  ]
}
```

```html
<button class="text-red">按钮</button>
```
presetTheme生成的相关样式变量为
```css
:root:{
  --theme-colors-red:255, 0, 0
}
```
当前想要的生成结果
```css
:root:{
  --theme-colors-red:255, 0, 0,
  --theme-colors-green:0, 255, 0
}
```

无视在源码中是否有使用到对应的css变量，直接全部生成。新增一个配置开关?
