### ISSUE TITLE
media query in config `safelist` got wrong output `:root` css

### ISSUE THREAD

**Issue by wtto00** [unpreset/unocss-preset-theme#68]
uno.config.ts
```ts
import { defineConfig, presetUno } from 'unocss'
import presetTheme from 'unocss-preset-theme'

export default defineConfig({
  presets: [
    presetUno(),
    presetTheme({
      theme: {
        dark: {
          colors: {
            foreground: '#FFF',
            background: '#0D0D0D',
          },
        },
      },
    }),
  ],
  theme: {
    colors: {
      foreground: '#000',
      background: '#FFF',
    },
  },
  safelist: ['md:text-sm']
})
```

The output css is:
```css
/* layer: theme */
@media (min-width: 768px){
:root{font-size:0.875rem;line-height:1.25rem;}
}
/* layer: default */
@media (min-width: 768px){
.md\:text-sm{font-size:0.875rem;line-height:1.25rem;}
}
```

`:root{font-size:0.875rem;line-height:1.25rem;}` should't be generated.

[Example playground](https://unocss.dev/play/?html=DwEwlgbgBAfAUMA9OC8g&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFCRY5SjRgAVABaoQqNhy59BwgLQVqtbTCUqxo1AA9J8NOgCGvADbWM2PAWIAKBKLjT9MKgAuOABtH18-WQYIDwBKEnDfPVlFZVQvRIijNODvCPyUWygAa1zMgrgBCAdoIMRyirZoVCIOfmRg7gBiADE%2B7gTGgoAjWwFi1oh2zq6ABgARBYWBhvzmQcb1hq21%2BPCAXQ3slTL8qpqoOryC9GbJ6Z452dmVitHx%2B6wOx76e14idiwNlRbOhUA5gFQYMEQtwQB0YBYYNoqCBuPtRMxYqIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9Ns8jxp5k0BhAVzjCVScAykMa4CAXyA)
