### ISSUE TITLE
[Bug Report] Can't set dark to default theme

### ISSUE THREAD

**Issue by wzc520pyfm** [unpreset/unocss-preset-theme#77]
When I set `selectors` to: 

```css
presetTheme({
  theme: { dark: {} },
  selectors: { light: ':root, .light', dark: '.dark' }
})
```

it will generate css:
```css
:root, .light {}
.dark: {}
```

But, When I set `selectors` to:
```css
presetTheme({
  theme: { light: {} },
  selectors: { dark: ':root, .dark', light: '.light' }
})
// I hope generated `:root, .dark {}`
```
it can not generate css.
